# Generated by Django 4.0.4 on 2022-05-03 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 3, 16, 9, 44, 69162)),
        ),
    ]
